services:
  postgres:
    image: postgres
    env_file: ./.env
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    volumes:
      - ../backend/db/migrations:/docker-entrypoint-initdb.d/
    ports:
        - "5555:5432"
  pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_LISTEN_PORT: 80
      ports:
        - 15432:80
      volumes:
        - pgadmin:/var/lib/pgadmin
      depends_on:
        - postgres
  api:
      build: ../backend
      restart: unless-stopped
      ports:
        - 1234:5550
      environment:
        - PGDATABASE=$POSTGRESDB_DATABASE
        - PGUSER=$POSTGRESDB_USER
        - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
        - PGHOST=postgres
        - PGPORT=5432
        - PORT=5550
      depends_on:
        - postgres
  frontend:
      build: 
        args:
          - REACT_APP_API_URL=http://localhost:1234
        context: ../frontend
      volumes:
      - ../frontend:/frontend
      env_file: ./.env
      restart: always
      ports:
        - 3000:80
      depends_on:
        - api
volumes:
  postgres:
  pgadmin: