services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpassword"
    volumes:
      - ../backend/db/migrations:/docker-entrypoint-initdb.d/
    ports:
        - "5555:5432"
  pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_LISTEN_PORT: 80
      ports:
        - 15432:80
      volumes:
        - pgadmin:/var/lib/pgadmin
      depends_on:
        - postgres
volumes:
  postgres:
  pgadmin: